import Navbar from "@/components/navbar/page";
import Footer from "@/components/footer/page"
import { Inter } from "next/font/google";

// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "First React",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/> </body>
    </html>
  );
}
